### ISSUE TITLE
onPlayerEditAttachedObject parameters ignored

### ISSUE THREAD

**Issue by Bebrazmogis** [Shoebill/shoebill-runtime#3]
When player is editing an attached object, new coordinates are passed to OnPlayerEditAttachedObject. 

The new offset, rotation, scale values and response are ignored in [shoebill](https://github.com/Shoebill/shoebill-runtime/blob/master/src/main/java/net/gtaun/shoebill/SampEventDispatcher.java#L899)

I believe those values should be passed to `PlayerEditAttachedObjectEvent` event. 

More info [here](http://forum.sa-mp.com/showpost.php?p=3632205&postcount=520) and [here](http://forum.sa-mp.com/showpost.php?p=3632242&postcount=521)

**Comment by 123marvin123** [comment]
Thanks, this is fixed with commit 616f1d52a6aceda36eebebf95b57fccaf9fb69c4 and 092b722e372daa7521926acf188a02cf35d65f57
