### ISSUE TITLE
MAX_CLASSES is out dated

### ISSUE THREAD

**Issue by Bebrazmogis** [Shoebill/shoebill-runtime#4]
`MAX_CLASSES` in [SampObjectStoreImpl](https://github.com/Shoebill/shoebill-runtime/blob/master/src/main/java/net/gtaun/shoebill/SampObjectStoreImpl.java#L53) is outdated. 

As of 0.3.7 the maximum amount of classes is 312.

**Comment by 123marvin123** [comment]
Thanks, it's fixed with commit efff67816924ad87c083765a91eb29941ae1b971.
