### ISSUE TITLE
Failed to collect dependencies

### ISSUE THREAD

**Issue by douq** [Shoebill/shoebill-runtime#6]
Moin,

seit gestern versuche ich das Shoebill Projekt bei mir zum Laufen zu bringen aber leider werde ich die ganze Zeit mit Fehlermeldungen gequält, die ich auch durch Neuinstallation und Google nicht lösen konnte.

Die Ausgabe die ich erhalte ist folgende: https://pastebin.com/NAL9NHae

Offline-Modus ist aus, JDK und das Paket habe ich noch einmal komplett neuinstalliert / runtergeladen. Als Basis für Shoebill nutze ich das Paket "Full server package (0.3.7 R2)" aus dem englischen Forum. 

Tipps / Anregungen fürs weitere Vorgehen oder gar die Lösung? :)

**Comment by Double-O-Seven** [comment]
Du musst das repository anpassen, es ist nicht mehr gtaun.net, sondern sampx.ru. Schau am besten wie es in den pom.xml Files vom Source Code ist.

**Comment by Double-O-Seven** [comment]
``<repositories>
        <repository>
            <id>gtaun-public-repo</id>
            <name>GTAUN Public Repository</name>
            <url>https://repo.sampx.ru/repository/maven-public/</url>
        </repository>
    </repositories>``
